---
- hosts: all
  user: root

  pre_tasks:
    - name: Install dependancies
      apt: name=$item state=present update-cache=yes
      with_items:
        - python-software-properties
        - python-virtualenv
        - python-apt
      environment:
        http_proxy: http://134.226.112.43:8080
        https_proxy: http://134.226.112.43:8080

  roles:
    - role: proxy
      proxy_server: proxy.tchpc.tcd.ie
      proxy_port: 8080
      socks_server: 134.226.112.43
      socks_port: 1080

    - role: common

  post_tasks:
    ## common step to get files on to system
    - name: copy up binaries
      copy: src=files/Ubuntu-12.10-opennebula-4.0.1-1.tar.gz dest=/tmp/Ubuntu-12.10-opennebula-4.0.1-1.tar.gz

    - name: unpack files
      command: chdir=/tmp creates=/tmp/opennebula-4.0.1-1/opennebula_4.0.1-1_amd64.deb tar xf Ubuntu-12.10-opennebula-4.0.1-1.tar.gz

    - name: /etc/hosts
      template: src=templates/hosts dest=/etc/hosts owner=root group=root

    - name: Generate_keys for root
      user: name=root generate_ssh_key=yes

    - name: Fetch generated public key from frontend root account
      fetch: src=$item dest=private/root/ flat=yes
      with_items:
        - /root/.ssh/id_rsa.pub
        - /root/.ssh/id_rsa

    - name: Upload ssh keypair and config from the frontend node for root account
      copy: src=private/root/$item dest=/root/.ssh/$item owner=root group=root mode=0600
      with_items:
        - id_rsa.pub
        - id_rsa

    - name: Upload ssh config
      copy: src=files/insecure_config dest=/root/.ssh/config owner=root group=root mode=0600

    - name: Install authorized_keys for root
      authorized_key: user=root key="{{ lookup('file', 'private/root/id_rsa.pub') }}" state=present

    - name: Install ntp
      apt: name=ntp state=present

    - name: Install ntp.conf
      template: src=templates/ntp.conf dest=/etc/ntp.conf

    - name: Restart ntp service
      service: name=ntp state=restarted

    - name: Make sure idmapd.conf has correct domain
      template: src=templates/idmapd.conf dest=/etc/idmapd.conf

- hosts: opennebula_frontend
  user: root

  roles:
    - frontend

- hosts: opennebula_compute
  user: root

  roles:
    - compute
