---
- hosts: all
  user: root

  pre_tasks:
    - name: Install dependancies
      apt: name=$item state=present update-cache=yes
      with_items:
        - python-software-properties
        - python-virtualenv
        - python-apt
      environment:
        http_proxy: http://134.226.112.43:8080
        https_proxy: http://134.226.112.43:8080

  roles:
    - role: proxy
      proxy_server: proxy.tchpc.tcd.ie
      proxy_port: 8080
      socks_server: 134.226.112.43
      socks_port: 1080

    - role: common

  post_tasks:
    ## common step to get files on to system
    - name: copy up binaries
      copy: src=files/Ubuntu-12.10-opennebula-4.0.1-1.tar.gz dest=/tmp/Ubuntu-12.10-opennebula-4.0.1-1.tar.gz

    - name: unpack files
      command: chdir=/tmp creates=/tmp/opennebula-4.0.1-1/opennebula_4.0.1-1_amd64.deb tar xf Ubuntu-12.10-opennebula-4.0.1-1.tar.gz

- hosts: opennebula_frontend
  user: root

  tasks:
    ## install and configure frontend machine
    - name: install debian packages
      shell: creates=/etc/one/oned.conf dpkg -i /tmp/opennebula-4.0.1-1/*.deb
      ignore_errors: True

    - name: fix up dependencies
      command: apt-get install -y -f

    - name: install dependancies
      apt: name=$item state=present
      with_items:
        - make
        - gcc
        - g++
        - libsqlite3-dev
        - libcurl4-openssl-dev
        - libmysqlclient-dev
        - rake
        - libxml2-dev
        - libxslt1-dev

    - name: install ruby dependancies
      gem: name=$item state=present
      with_items:
        - sqlite3
        - amazon-ec2
        - curb
        - mysql
        - net-ldap

    - name: install sunstone configruation
      template: src=templates/sunstone-server.conf dest=/etc/one/sunstone-server.conf
      notify:
        - restart sunstone

    - name: start sunstone
      service: name=opennebula-sunstone state=started enabled=yes

    ## generate public/private keys, this should be shared across the ONE frontend and nodes in the oneadmin account
    - name: Generate_keys for oneadmin
      user: name=oneadmin generate_ssh_key=yes

    - name: Fetch generated public key from frontend oneadmin account
      fetch: src=$item dest=private/ flat=yes
      with_items:
        - /var/lib/one/.ssh/id_rsa.pub
        - /var/lib/one/.ssh/id_rsa

    - name: Install insecure config for oneadmin
      action: copy src=files/insecure_config dest=/var/lib/one/.ssh/config owner=oneadmin group=cloud mode=0600

  handlers:
    - name: restart sunstone
      service: name=opennebula-sunstone state=restarted

- hosts: opennebula_compute
  user: root

  tasks:
    ## install kvm node
    - name: install debian packages
      command: dpkg -i /tmp/opennebula-4.0.1-1/$item
      with_items:
        - opennebula-common_4.0.1-1_all.deb
        - opennebula-node_4.0.1-1_all.deb
      ignore_errors: True

    - name: fix up dependencies
      command: apt-get install -y -f

    - name: install kvm dependancies
      apt: name=$item state=present
      with_items:
        - qemu

    ## install public/private keys, this should be shared across the ONE frontend and nodes in the oneadmin account
    - name: Install authorized_keys for oneadmin
      authorized_key: user=oneadmin key="{{ lookup('file', 'private/id_rsa.pub') }}" state=present

    - name: Install insecure config for oneadmin
      action: copy src=files/insecure_config dest=/var/lib/one/.ssh/config owner=oneadmin group=cloud mode=0600

    ## configure the KVM driver
    - name: install qemu.conf
      template: src=templates/qemu.conf dest=/etc/libvirt/qemu.conf

    - name: install libvirtd.conf
      template: src=templates/libvirtd.conf dest=/etc/libvirt/libvirtd.conf

    - name: install libvirt-bin
      template: src=templates/libvirt-bin dest=/etc/default/libvirt-bin

    - name: install udev rules
      template: src=templates/60-qemu-kvm.rules dest=/etc/udev/rules.d/60-qemu-kvm.rules
