---
- hosts: all
  user: root

  pre_tasks:
    - name: Install dependancies
      apt: name=$item state=present update-cache=yes
      with_items:
        - python-software-properties
        - python-virtualenv
        - python-apt
      environment:
        http_proxy: http://134.226.112.43:8080
        https_proxy: http://134.226.112.43:8080

  roles:
    - role: proxy
      proxy_server: proxy.tchpc.tcd.ie
      proxy_port: 8080
      socks_server: 134.226.112.43
      socks_port: 1080

    - role: common

  post_tasks:
    ## common step to get files on to system
    - name: copy up binaries
      copy: src=files/Ubuntu-12.10-opennebula-4.0.1-1.tar.gz dest=/tmp/Ubuntu-12.10-opennebula-4.0.1-1.tar.gz

    - name: unpack files
      command: chdir=/tmp creates=/tmp/opennebula-4.0.1-1/opennebula_4.0.1-1_amd64.deb tar xf Ubuntu-12.10-opennebula-4.0.1-1.tar.gz

    - name: /etc/hosts
      template: src=templates/hosts dest=/etc/hosts owner=root group=root

- hosts: opennebula_frontend
  user: root

  roles:
    - frontend

- hosts: opennebula_compute
  user: root

  roles:
    - compute
