---
    ## boiler plate
    - name: Install dependancies
      apt: name=$item state=present update-cache=yes
      with_items:
        - git
        - bzr
        - etckeeper
        - curl
        - avahi-daemon
        - avahi-utils
        - avahi-discover
        - avahi-dnsconfd
