---
- hosts: opennebula_frontend
  user: root

  tasks:
    - apt: name=haproxy state=present
    - template: src=../templates/haproxy/haproxy.cfg dest=/etc/haproxy/haproxy.cfg
      notify: restart haproxy
    - copy: src=../files/haproxy/haproxy dest=/etc/default/haproxy
      notify: restart haproxy
    - service: name=haproxy enabled=yes

  handlers:
    - name: start haproxy
      service: name=haproxy state=started enabled=yes

    - name: restart haproxy
      service: name=haproxy state=restarted enabled=yes
