# for ubuntu 12.04 hosts, run this playbook as... "ansible-playbook -i hosts PLAYBOOK.yml -k"
---
- hosts: opennebula_frontend
  user: root

  tasks:
    - name: Create ranged vnet template 
      template: src=../templates/vnet_ranged.net dest=/tmp/vnet_ranged.net

    - name: Create vnet
      command: su - oneadmin -c "onevnet create /tmp/vnet_ranged.net"
