# for ubuntu 12.04 hosts, run this playbook as... "ansible-playbook -i hosts PLAYBOOK.yml -k"
---
- hosts: opennebula_frontend
  user: root

  tasks:
    - name: Create datastore template 
      template: src=../templates/one_ds_ceph dest=/tmp/one_ds_ceph

    - name: Create ceph datastore
      sudo_user: oneadmin
      command: onedatastore create /tmp/one_ds_ceph
